accounts/urls.py
from django.conf.urls import url, patterns, include

urlpatterns = patterns('accounts.views',
    url(r'^roleplay-test/$', 'roleplay_test', name='roleplay-test'),
    url(r'^login/$', 'accounts_login', name='login'),
    url(r'^logout/$', 'accounts_logout', name='logout'),
    url(r'^register/$', 'accounts_register', name='register'),
    url(r'^user_panel/$', include(patterns('accounts.views',
        url(r'^$', 'user_panel', name='index'),
    ), namespace='user_panel')),
    url(r'^friends/', include(patterns('accounts.views',
        url(r'^$', 'friends_index', name='index'),
        url(r'^requests', 'friends_requests', name='requests'),
        url(r'^send-request/(?P<friend_pk>[\d]+)/$',
            'friends_send_request', name='send_request'),
        url(r'^delete-request/(?P<pk>[\d]+)/$', 'friends_delete_request',
            name='delete_request'),
        url(r'^accept-request/(?P<pk>[\d]+)/$', 'friends_accept_request',
            name='accept_request'),
        url(r'^delete-friend/(?P<friend_pk>[\d]+)/$', 'friends_delete_friend',
            name='delete_friend'),
    ), namespace='friends')),
    url(r'^~(?P<slug>[-\w]+)/', include(patterns('accounts.views',
        url(r'^$', 'accounts_profile_index', name='index'),
        url(r'^characters/$', 'accounts_profile_characters', name='characters'),
        url(r'^about-me/$', 'accounts_profile_about_me', name='about_me'),
        url(r'^friends/$', 'accounts_profile_friends', name='friends'),
        url(r'^logs/$', 'accounts_profile_logs', name='logs'),
    ), namespace='profile')),
)

blog/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('blog.views',
    url(r'^(?:page-(?P<page>[\d]+)/)?$', 'index', name='index'),
    url(r'^(?P<slug>[-\w]+)/$', 'post', name='post'),
)

cloudmta/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Django
    url(r'^admin/', include(admin.site.urls)),

    # Third-party

    # Mine
    url(r'^$', 'pages.views.homepage', name='homepage'),
    url(r'^characters/', include('characters.urls', namespace='characters')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^vehicles/', include('vehicles.urls', namespace='vehicles')),
    url(r'^groups/', include('groups.urls', namespace='groups')),
    url(r'^doors/', include('doors.urls', namespace='doors')),
    url(r'^page/', include('pages.urls', namespace='pages')),
    url(r'^wiki/', include('wiki.urls', namespace='wiki')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
]

front/templates/includes/footer.html
{% load i18n %}
{% load staticfiles %}
<footer id="cloudmta-footer">
  <div id="footer-menu">
    <div class="row">
      <div class="medium-4 columns">
        <h2>{% trans 'Menu #1' %}</h2>
        <ul class="no-bullet">
          <li><a href="#">Link</a></li>
          <li><a href="#">Link</a></li>
          <li><a href="#">Link</a></li>
        </ul>
      </div>
      <div class="medium-4 columns">
        <h2>{% trans 'Menu #2' %}</h2>
        <ul class="no-bullet">
          <li><a href="#">Link</a></li>
          <li><a href="#">Link</a></li>
          <li><a href="#">Link</a></li>
        </ul>
      </div>
      <div class="medium-4 columns">
        <h2>{% trans 'Menu #3' %}</h2>
        <ul class="no-bullet">
          <li><a href="#">Link</a></li>
          <li><a href="#">Link</a></li>
          <li><a href="#">Link</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div id="footer-credits">
    <div class="row">
      <div class="medium-5 columns">
        <a href="{% url 'homepage' %}">
          <img src="{% static 'img/logo-white.svg' %}" alt="Logo CloudMTA"
            class="cloudmta-footer-logo">
        </a>
      </div>
      <div class="medium-7 columns" id="social-columns">
        <ul class="inline-list">
          <li>
            <a href="http://fb.com/cloudmta">
              <i class="fa fa-facebook"></i>
            </a>
          </li>
          <li>
            <a href="http://twitter.com">
              <i class="fa fa-twitter"></i>
            </a>
          </li>
          <li>
            <a href="http://steam.com">
              <i class="fa fa-steam"></i>
            </a>
          </li>
          <li>
            <a href="http://youtube.com">
              <i class="fa fa-youtube"></i>
            </a>
          </li>
      </div>
    </div>
    <div class="row">
      <div class="medium-6 columns" id="copyright-column">
        {% trans '&copy; 2015 CloudMTA' %}
      </div>
      <div class="medium-6 columns" id="powered-by-column">
        <p class="powered-by-label">{% trans 'Projekt istnieje dzięki' %}</p>
        <ul class="inline-list">
          <li>
            <a href="http://multitheftauto.com">
              <img class="powered-by-img"
                src="{% static 'img/powered-by/mta-logo.png' %}"
                alt="Multi Theft Auto San Andreas"
                title="Multi Theft Auto San Andreas">
            </a>
          </li>
          <li>
            <a href="http://djangoproject.com">
              <img class="powered-by-img"
                src="{% static 'img/powered-by/django-logo-white.svg' %}"
                alt="Django web framework" title="Django web framework">
            </a>
          </li>
          <li>
            <a href="http://mysql.com">
              <img class="powered-by-img"
                src="{% static 'img/powered-by/mysql-logo.svg' %}"
                alt="MySQL" title="MySQL">
            </a>
          </li>
          <li>
            <a href="http://nginx.org">
              <img class="powered-by-img"
                src="{% static 'img/powered-by/nginx-logo.svg' %}"
                alt="nginx" title="nginx">
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

front/templates/includes/header.html
{% load i18n %}
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><a href="{% url 'homepage' %}">CloudMTA</a></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>{% trans 'Menu' %}</span></a></li>
  </ul>

  <section class="top-bar-section">
    {# Right Nav Section #}
    <ul class="right">
      <li class="has-form">
        <a class="button">
          {% blocktrans %}{{ ONLINE_PLAYER_NUMBER }} graczy online{% endblocktrans %}
        </a>
      </li>
      {% if not request.user.is_authenticated %}
        <li{% if 'register' in request.path %} class="active"{% endif %}>
          <a href="{% url 'accounts:register' %}">
            {% trans 'Rejestracja' %}
          </a>
        </li>
        <li{% if 'login' in request.path %} class="active"{% endif %}>
          <a href="{% url 'accounts:login' %}">
            {% trans 'Logowanie' %}
          </a>
        </li>
      {% else %}
      <li class="has-dropdown{% if request.user.username in request.path %} active{% endif %}">
        <a href="{{ request.user.get_absolute_url }}">
          {{ request.user }}
        </a>
        <ul class="dropdown">
          <li{% if request.path == request.user.get_absolute_url %} class=" active"{% endif %}>
            <a href="{{ request.user.get_absolute_url }}">
              {% trans 'Profil' %}
            </a>
          </li>
          <li{% if 'characters' in request.path %} class="active"{% endif %}>
            <a href="{% url 'characters:index' %}">
              {% trans 'Twoje postacie' %}
            </a>
          </li>
          <li{% if 'friends' in request.path %} class="active"{% endif %}>
            <a href="{% url 'accounts:friends:index' %}">
              {% trans 'Twoi znajomi' %}
            </a>
          </li>
          <li{% if 'user_panel' in request.path %} class="active"{% endif %}>
            <a href="{% url 'accounts:user_panel:index' %}">
              {% trans 'Panel uzytkownika' %}
            </a>
          </li>
          {% if request.user.is_staff %}
            <li>
              <a href="{% url 'admin:index' %}">
                {% trans 'Administracja' %}
              </a>
            </li>
          {% endif %}
          <li>
            <a href="{% url 'accounts:logout' %}">
              {% trans 'Wyloguj' %}
              <span class="right">
                <i class="fa fa-sign-out"></i>
              </span>
            </a>
          </li>
        </ul>
      </li>
      {% endif %}
    </ul>

    <!-- Left Nav Section -->
    <ul class="left">
      {% url 'homepage' as homepage_url %}
      <li{% if request.path == homepage_url %} class="active"{% endif %}>
        <a href="{% url 'homepage' %}">
          <i class="fa fa-home"></i>
        </a>
      </li>
      <li{% if 'wiki' in request.path %} class="active"{% endif %}>
        <a href="{% url 'wiki:index' %}">
          {% trans 'Wiki' %}
        </a>
      </li>
      <li{% if 'blog' in request.path %} class="active"{% endif %}>
        <a href="{% url 'blog:index' %}">
          {% trans 'Blog' %}
        </a>
      </li>
      <li>
        <a href="{{ FORUM_LINK }}">
          {% trans 'Forum' %}
        </a>
      </li>
    </ul>
  </section>
</nav>

front/templates/includes/header_banner.html
<div class="header-banner">
  <div class="row">
    <div class="large-12 columns">
      <h1>
        {% if url %}<a href="{{ url }}">{% endif %}
          {{ text }}
        {% if url %}</a>{% endif %}
      </h1>
    </div>
  </div>
</div>

front/templates/includes/messages.html
{% if messages %}
	<div class="row">
		<div class="12-large columns">
		    {% for message in messages %}
	    		<div data-alert class="alert-box alert-alert expand {% if message.tags %} {{ message.tags }}{% endif %}">
					{{ message }}
					<a href="#" class="close">&times;</a>
				</div>
		    {% endfor %}
		</div>
	</div>
{% endif %}

front/templates/includes/pagination.html
<div class="pagination-centered">
  <ul class="pagination">
    <li class="arrow{% if not items.has_previous %} unavailable{% endif %}">
      <a href="{% if items.has_previous %}{% url 'blog:index' items.previous_page_number %}{% endif %}">&laquo;</a>
    </li>
    <li class="unavailable"><a href="{% url 'blog:index' items.number %}">{{ items.number }}</a></li>
    <li class="unavailable"><a href="">of</a></li>
    <li><a href="{% url 'blog:index' items.paginator.num_pages %}">{{ items.paginator.num_pages }}</a></li>
    <li class="arrow{% if not items.has_next %} unavailable{% endif %}">
      <a href="{% if items.has_next %}{% url 'blog:index' items.next_page_number %}{% endif %}">&raquo;</a>
    </li>
  </ul>
</div>