blog/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('blog.views',
    url(r'^(?:page-(?P<page>[\d]+)/)?$', 'index', name='index'),
    url(r'^(?P<slug>[-\w]+)/$', 'post', name='post'),
)

characters/urls.py
from django.conf.urls import url, include, patterns

urlpatterns = patterns('characters.views',
    url(r'^$', 'characters_index', name='index'), # Main URL for list of all user's characters
    url(r'^create/$', 'characters_create', name='create'), # Create a character

    # Character profile URLs
    url(r'^(?P<pk>[\d]+)/', include(patterns('characters.views',
        url(r'^$', 'characters_show_index', name='index'),
        url(r'^items/$', 'characters_show_items', name='items'),
        url(r'^settings/$', 'characters_show_settings', name='settings'),
        url(r'^vehicles/$', 'characters_show_vehicles', name='vehicles'),
        url(r'^doors/$', 'characters_show_doors', name='doors'),
        url(r'^groups/$', 'characters_show_groups', name='groups'),
        url(r'^group-invitations/(?P<invitation_id>[\d]+)/accept/$',
            'characters_show_group_invitations_accept',
            name='group_invitations_accept'),
        url(r'^group-invitations/(?P<invitation_id>[\d]+)/decline/$',
            'characters_show_group_invitations_decline',
            name='group_invitations_decline'),
    ), namespace='show'))
)

cloudmta/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Django
    url(r'^admin/', include(admin.site.urls)),

    # Third-party

    # Mine
    url(r'^$', 'pages.views.homepage', name='homepage'),
    url(r'^characters/', include('characters.urls', namespace='characters')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^vehicles/', include('vehicles.urls', namespace='vehicles')),
    url(r'^groups/', include('groups.urls', namespace='groups')),
    url(r'^doors/', include('doors.urls', namespace='doors')),
    url(r'^page/', include('pages.urls', namespace='pages')),
    url(r'^wiki/', include('wiki.urls', namespace='wiki')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
]

characters/models.py
import random
import datetime
import hashlib
from django.db import models
from django.utils.translation import ugettext as _
from django_unixdatetimefield import UnixDateTimeField
from django.conf import settings
from django.core.validators import RegexValidator
from django.core.urlresolvers import reverse
from django.db.models import get_model

class Character(models.Model):
    """Model przechowujący informacje o postaciach"""
    id = models.AutoField(db_column='ID', primary_key=True)
    memberid = models.ForeignKey(settings.AUTH_USER_MODEL,
        verbose_name=_('konto'), related_name='characters',
        related_query_name='character')
    NAME_VALIDATOR =  NAME_VALIDATOR = RegexValidator(r'^([A-Za-z]{2,})([\s][A-Za-z]{2,})?([\s][A-Za-z]{2,})$')
    name = models.CharField(max_length=22, validators=[NAME_VALIDATOR],
        verbose_name=_('imię i nazwisko'), help_text=_('drugie imię opcjonalne,'
        ' odstępy rozdzielać spacją.'), unique=True)

    def generate_facecode():
        """Generuje kod twarzy

        Gdy postać jest tworzona, wygeneruj losowy ciąg znaków
        i sprawdź jego unikalność w bazie danych."""
        while True:
            facecode = ''
            for i in range(6):
                facecode += random.choice('ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789').upper()
            if not Character.objects.filter(facecode=facecode).count():
                return facecode
    facecode = models.CharField(db_column='faceCode', default=generate_facecode,
        verbose_name=_('kod twarzy'), max_length=6, unique=True)

    def generate_shortdna_code():
        """Generuje krótki kod DNA i sprawdza jego unikalność"""
        while True:
            shortdna = ''
            for i in range(4):
                shortdna += random.choice('ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789').lower()
            if not Character.objects.filter(shortdna=shortdna).count():
                return shortdna
    shortdna = models.CharField(db_column='shortDNA', max_length=4, unique=True,
        verbose_name=_('krótki kod DNA'), help_text=_('używany m.in. do '
        'kominiarek'), default=generate_shortdna_code)

    def generate_dna_code():
        """Generuje kod DNA i sprawdza jego unikalność"""
        while True:
            random_number = str(random.getrandbits(128))
            dna = hashlib.md5(random_number.encode('utf-8')).hexdigest().upper()
            if not Character.objects.filter(dna=dna).count():
                return dna
    dna = models.CharField(db_column='DNA', max_length=255, unique=True,
        verbose_name=_('DNA'), default=generate_dna_code)
    hp = models.FloatField(default=100, verbose_name=_('punkty życia'))
    skin = models.PositiveSmallIntegerField(default=1,
        verbose_name=_('ID Skina'))
    x = models.FloatField(blank=True, null=True, verbose_name=_('pozycja X'))
    y = models.FloatField(blank=True, null=True, verbose_name=_('pozycja Y'))
    z = models.FloatField(blank=True, null=True, verbose_name=_('pozycja Z'))
    angle = models.FloatField(blank=True, null=True, verbose_name=_('kąt'))
    dimension = models.PositiveIntegerField(default=0, verbose_name=_('wymiar'))
    interior = models.PositiveIntegerField(default=0, verbose_name=_('wnętrze'))
    money = models.PositiveIntegerField(default=settings.RP_DEFAULT_CHARACTER_MONEY,
        verbose_name=_('gotówka'))
    bwtime = models.PositiveIntegerField(db_column='bwTime', default=0,
        verbose_name=_('czas BW'), help_text=_('w sekundach'))
    ajtime = models.PositiveIntegerField(db_column='ajTime', default=0,
        verbose_name=_('czas AJ'), help_text=_('w sekundach'))
    onlinetime = models.PositiveIntegerField(db_column='onlineTime', default=0,
        verbose_name=_('czas w grze'), help_text=_('w sekundach'))
    afktime = models.PositiveIntegerField(db_column='afkTime', default=0,
        verbose_name=_('czas AFK'), help_text=_('w sekundach'))
    SEX_CHOICES = (
        (1, _('Mężczyzna')),
        (2, _('Kobieta')),
    )
    sex = models.PositiveSmallIntegerField(choices=SEX_CHOICES,
        verbose_name=_('płeć'))
    ingame = models.BooleanField(db_column='inGame', verbose_name=_('postać w '
        'grze'), default=False)
    lastvisit = UnixDateTimeField(db_column='lastVisit',
        verbose_name=_('ostatnia wizyta'), null=True, blank=True)
    blocked = models.BooleanField(default=False, verbose_name=_('zablokowana'))
    hide = models.BooleanField(default=False, verbose_name=_('ukryta'))
    dob = models.DateField(verbose_name=_('data urodzenia'))
    activated = models.BooleanField(default=True, verbose_name=_('aktywowana'),
        help_text=_('stare, nie tykać'))

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        """Link do panelu postaci"""
        return reverse('characters:show:index', kwargs={'pk': self.pk})

    class Meta:
        db_table = '_characters'
        verbose_name = _('postać')
        verbose_name_plural = _('postacie')

    def get_skin_static_url(self):
        """Pobierz link do skinu użycia w {% static %}"""
        return "%s/%d.%s" % (settings.RP_SKINS_STATIC_DIRECTORY,
            self.skin, settings.RP_SKINS_IMG_FORMAT)

    @staticmethod
    def format_time(seconds):
        """Formatuj czas z sekund do godzin i minut"""
        seconds = int(seconds)
        m, s = divmod(seconds, 60)
        h, m = divmod(m, 60)
        return "%dh %02dmin" % (h, m)

    def format_online_time(self):
        """Sformatuj czas online"""
        return self.format_time(self.onlinetime)

    def format_afk_time(self):
        """Sformatuj czas AFK"""
        return self.format_time(self.afktime)

    def format_bw_time(self):
        """Sformatuj czas BW"""
        return self.format_time(self.bwtime)

    def format_aj_time(self):
        """Sformatuj czas AJ"""
        return self.format_time(self.ajtime)

    def items(self):
        """Pobierz obiekty przedmiotów tej postaci"""
        return get_model('items', 'Item').objects.filter(owner=self.pk,
            ownertype=settings.RP_ITEM_OWNER_TYPE_ID_CHARACTER)

    def vehicles(self):
        """Pobierz pojazdy postaci"""
        return get_model('vehicles', 'Vehicle').objects.filter(ownerid=self.pk,
            ownertype=settings.RP_VEHICLE_OWNER_TYPE_ID_CHARACTER)

    def doors(self):
        """Pobierz drzwi postaci"""
        return get_model('doors', 'Door').objects.filter(owner=self.pk,
            ownertype=settings.RP_DOOR_OWNER_TYPE_ID_CHARACTER)

class StartSkin(models.Model):
    """Przechowuje informacje o skinach dostępnych przy tworzeniu postaci"""
    skin_id = models.PositiveSmallIntegerField(verbose_name=_('ID skina'), unique=True)
    SEX_CHOICES = (
        (1, _('mężczyzna')),
        (2, _('kobieta')),
    )
    sex = models.PositiveSmallIntegerField(choices=SEX_CHOICES,
        verbose_name=_('płeć'))

    def __str__(self):
        return _("Startowy skin %d (%s)" % (self.skin_id, self.get_sex_display()[0]))

    class Meta:
        verbose_name = _('skin startowy')
        verbose_name_plural = _('skiny startowe')

    def get_static_url(self):
        """Pobierz link do skinu do użycia w {% static %}"""
        return "%s/%d.%s" % (settings.RP_SKINS_STATIC_DIRECTORY,
            self.skin_id, settings.RP_SKINS_IMG_FORMAT)

class Facecode(models.Model):
    """Model zawiera informacje o aliasach nadanych dla innych postaci"""
    charid = models.ForeignKey('Character', db_column='charID',
        verbose_name=_('Postać'), related_name='facecodes')
    facecode = models.CharField(db_column='faceCode', max_length=10,
        verbose_name=_('Kod twarzy'), help_text=_('Kod twarzy postaci, do '
        'której przypisany jest alias.'))
    name = models.CharField(max_length=100, verbose_name=_('Alias postaci'))

    class Meta:
        db_table = '_faceCodes'
        verbose_name = _('kod twarzy')
        verbose_name_plural = _('kody twarzy')

class LoginLog(models.Model):
    """Przechowuje logi logowania użytkownika"""
    id = models.AutoField(db_column='ID', primary_key=True)
    charid = models.ForeignKey('Character', db_column='charID',
        verbose_name=_('postać'))
    ip = models.GenericIPAddressField(verbose_name=_('adres IP'),
        default='127.0.0.1')
    serial = models.CharField(blank=True, null=True, verbose_name=_('serial'),
        max_length=settings.RP_SERIAL_LENGTH)
    time = UnixDateTimeField(verbose_name=_('data logowania'), blank=True,
        null=True)

    def __str__(self):
        return _("%s (%s)" % (self.charid, self.serial))

    class Meta:
        db_table = '_login_logs'
        verbose_name = _('log logowania')
        verbose_name_plural = _('logi logowania')

class PenaltyLog(models.Model):
    """Logi kar"""
    id = models.AutoField(db_column='ID', primary_key=True)
    serial = models.CharField(max_length=settings.RP_SERIAL_LENGTH,
        verbose_name=_('serial'))
    ip = models.GenericIPAddressField(verbose_name=_('adres IP'))
    character = models.ForeignKey('characters.Character',
        verbose_name=_('postać'), db_column='userID',
        related_name='characters', related_query_name='character')
    admin = models.ForeignKey(settings.AUTH_USER_MODEL,
        verbose_name=_('administrator'), db_column='adminID',
        related_name='admins', related_query_name='admin')
    reason = models.TextField(verbose_name=_('powód'), blank=True, null=True)
    time = models.PositiveIntegerField(verbose_name=_('data nadania'))
    expire = models.PositiveIntegerField(verbose_name=_('data wygaśnięcia'),
        blank=True, null=True)
    PENALTY_TYPE_CHOICES = (
        (1, _('kick')),
        (2, _('admin jail')),
        (3, _('warn')),
        (4, _('ban')),
        (5, _('blokada postaci')),
    )
    penalty_type = models.PositiveSmallIntegerField(choices=PENALTY_TYPE_CHOICES,
        verbose_name=_('typ kary'), db_column='type')

    # def __str__(self):
    # TODO(tomaszkn): Nie wiem czemu to nie działa (?)

characters/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import user_passes_test, login_required
from django.contrib.auth import get_user_model
from django.conf import settings
from django.contrib import messages
from django.utils.translation import ugettext as _
from .models import Character, StartSkin
from .forms import CreateCharacterForm, CharacterSettingsForm

@login_required
def characters_index(request):
    """Wyświetl wszystkie postacie użytkownika"""
    characters = request.user.characters.all()
    return render(request, 'characters/index.html', {'characters': characters})

@login_required
@user_passes_test(get_user_model().has_passed_rp_test, 'accounts:roleplay-test')
@user_passes_test(get_user_model().can_create_character,
    'characters:index')
def characters_create(request):
    """Stwórz postać"""
    # Zapisz skiny startowe i podziel je na płci
    skins_1 = []
    skins_2 = []
    for s in StartSkin.objects.all():
        if s.sex == 1:
            skins_1.append(s)
        else:
            skins_2.append(s)
    start_skins = {1: skins_1, 2: skins_2}

    if request.method == 'POST':
        form = CreateCharacterForm(request.POST)
        if form.is_valid():
            character = form.save(commit=False)
            character.memberid = request.user
            character.save()
            return redirect('characters:show:index', pk=character.pk)
    else:
        form = CreateCharacterForm()
    return render(request, 'characters/create.html', {'form': form,
        'skins': start_skins})

def get_character_object(request, pk):
    """Zwróć obiekt postaci

    Funkcja zapobiega powtarzaniu kodu do pobierania obiektu postaci.
    Zwraca kod HTTP 404, jeżeli użytkownik nie jest właścicielem postaci."""
    return get_object_or_404(Character, pk=pk, memberid=request.user)

@login_required
def characters_show_index(request, pk):
    """Pokaż główną zakładkę w szczegółach postaci"""
    character = get_character_object(request, pk)
    return render(request, 'characters/show/index.html',
        {'character': character})

@login_required
def characters_show_items(request, pk):
    """Pokaż przedmioty postaci"""
    character = get_character_object(request, pk)
    items = character.items
    return render(request, 'characters/show/items.html',
        {'character': character, 'items': items})

@login_required
def characters_show_vehicles(request, pk):
    """Pokaż pojazdy postaci"""
    character = get_character_object(request, pk)
    vehicles = character.vehicles
    return render(request, 'characters/show/vehicles.html',
        {'character': character, 'vehicles': vehicles})

@login_required
def characters_show_doors(request, pk):
    """Pokaż pojazdy postaci"""
    character = get_character_object(request, pk)
    doors = character.doors
    return render(request, 'characters/show/doors.html',
        {'character': character, 'doors': doors})


@login_required
def characters_show_groups(request, pk):
    """Pokaż pojazdy postaci"""
    character = get_character_object(request, pk)
    groups = character.groups.all()
    invitations = character.groupinvitations.all()
    return render(request, 'characters/show/groups.html',
        {'character': character, 'groups': groups,
        'invitations': invitations})

@login_required
def characters_show_settings(request, pk):
    """Pokaż ustawienia w szczegółach postaci"""
    character = get_character_object(request, pk)
    if request.method == 'POST':
        form = CharacterSettingsForm(request.POST, instance=character)
        if form.is_valid():
            form.save()
            messages.success(request, _("Ustawienia postaci %s zostały "
                "zapisane." % character))
    else:
        form = CharacterSettingsForm(instance=character)
    return render(request, 'characters/show/settings.html',
        {'character': character, 'form': form})

@login_required
def characters_show_group_invitations_accept(request, pk, invitation_id):
    """Akceptuj zaproszenie do grupy"""
    character = get_character_object(request, pk)
    invitation = get_object_or_404(character.groupinvitations, pk=invitation_id)
    # Czy gracz nie jest w za dużej ilości grup?
    if character.groupmembers.all().count() >= settings.RP_MAX_GROUP_NUMBER:
        messages.error(request, _("Przekroczyłeś limit ilości grup na postać: "
            "%d" % settings.RP_MAX_GROUP_NUMBER))
        return redirect('characters:show:groups', character.pk)

    # Czy gracz nie jest już w tej grupie obecnie?
    if character.groupmembers.filter(groupid=invitation.group).count():
        messages.error(request, _("Postać już obecnie jest w tej "
            "grupie."))
        return redirect('characters:show:groups', character.pk)

    invitation.group.add_new_member(character=character)
    invitation.delete()
    messages.success(request, _("Zostałeś dodany do grupy"))
    return redirect('characters:show:groups', character.pk)

@login_required
def characters_show_group_invitations_decline(request, pk, invitation_id):
    """Odrzuć zaproszenie do grupy"""
    character = get_character_object(request, pk)
    invitation = get_object_or_404(character.groupinvitations, pk=invitation_id)
    invitation.delete()
    messages.success(request, _("Skasowano zaproszenie do grupy"))
    return redirect('characters:show:groups', character.pk)

front/templates/accounts/profile/ajax/about_me.html
{% load i18n %}
<h2>{% trans 'O mnie' %}</h2>
{% if not user.format_about_me %}
  {% trans 'Nic tutaj nie ma...' %}
{% else %}
  <hr>
  {{ user.format_about_me|safe }}
{% endif %}

front/templates/accounts/profile/ajax/characters.html
{% load staticfiles %}
{% load i18n %}
<h2>{% trans 'Postacie' %}</h2>
<ul class="characters-list large-block-grid-3 medium-block-grid-2 small-block-grid-1" data-equalizer>
  {% for character in user.characters.all %}
    <li>
      <a style="background-image: url({%if character.hide%}{% static 'img/skins/hidden.png' %}{%else%}{% static character.get_skin_static_url %}{%endif%})">
        <ul class="no-bullet">
          <li>
            <h2>{% if character.hide %} {% trans 'Postać ukryta' %} {% else %} {{ character }} {% endif %} </h2>
          </li>
          <li>{{ character.format_online_time }} </li>
        </ul>
      </a>
    </li>
  {% empty %}
    <li>
      <h1>{% trans 'Brak postaci' %}</h1>
    </li>
  {% endfor %}
</ul>

front/templates/accounts/profile/ajax/friends.html
{% load staticfiles %}
{% load i18n %}
<h2>{% trans 'Znajomi' %}</h2>
<ul class="large-block-grid-5 medium-block-grid-3 small-block-grid-2">
  {% for friend in user.friends.all %}
    <li>
      <a href="{{ friend.get_absolute_url }}">
        <div class="avatar-box avatar-medium" style="background-image: url({{ friend.get_avatar_url }})">
          <div class="avatar-box-username">{{ friend }}</div>
        </div>
      </a>
    </li>
  {% empty %}
    <li>{% trans 'Brak znajomych...' %}</li>
  {% endfor %}
</ul>

front/templates/accounts/profile/ajax/index.html
{% load i18n %}
<div class="row">
  <div class="large-4 small-12 columns">
    <h3>{% trans 'Informacje' %}</h3>
    <dl>
      {% if user.gender %}
        <dt><i class="fa fa-transgender"></i>{% trans 'Płeć' %}</dt>
        <dd>{{ user.get_gender_display|title }}</dd>
      {% endif %}
      {% if user.location %}
        <dt><i class="fa fa-compass"></i> {% trans 'Lokalizacja' %}</dt>
        <dd>{{ user.location }}</dd>
      {% endif %}
        <dt><i class="fa fa-heart"></i> {% trans 'Znajomi' %}</dt>
        <dd>Liczba znajomych: <strong>{{ user.friends.count }}</strong>
        <br>
        {% if request.user != user %}
          {% if user in request.user.friends.all %}
            <a href="{% url 'accounts:friends:delete_friend' user.pk %}">{% trans 'Usuń ze znajomych' %}</a>
          {% else %}
            <a href="{% url 'accounts:friends:send_request' user.pk %}">
              {% trans 'Zaproś do znajomych' %}
            </a>
          {% endif %}
        {% endif %}</dd>
        <dt><i class="fa fa-credit-card"></i> {% trans 'CloudPoints' %}</dt>
        <dd>Liczba punktow gracza: <strong>1503</strong></dd>
    </dl>
  </div>
  <div class="large-4 small-12 columns">
    <h3>{% trans 'Kontakt' %}</h3>
    <dl>
      {% if user.public_email %}
        <dt><i class="fa fa-envelope-o"></i> {% trans 'Adres email' %}</dt>
        <dd><a href="mailto:{{ user.email }}">{{ user.email }}</a></dd>
      {% endif %}
      {% if user.skype_id %}
        <dt><i class="fa fa-skype"></i> {% trans 'Skype' %}</dt>
        <dd><a href="skype:{{ user.skype_id }}">{{ user.skype_id }}</a></dd>
      {% endif %}
      {% if user.website %}
        <dt><i class="fa fa-globe"></i> {% trans 'Strona internetowa' %}</dt>
        <dd><a href="{{ user.website }}">{{ user.website }}</a></dd>
      {% endif %}
    </dl>
  </div>
  <div class="large-4 small-12 columns">
    <h3>{% trans 'Sieci społecznościowe' %}</h3>
    <ul class= "no-bullet">
      {% if user.facebook %}
      <li>
        <a class="button facebook expand" href="{{ user.facebook }}"><i class="fa fa-facebook"></i> facebook </a>
      </li>
      {% endif %}
      {% if user.twitter %}
      <li>
        <a class="button twitter expand" href="http://www.twitter.com/{{ user.twitter }}"><i class="fa fa-twitter"></i> twitter </a>
      </li>
      {% endif %}
      {% if user.youtube %}
      <li>
        <a class="button youtube expand" href="http://www.youtube.com/{{ user.youtube }}"><i class="fa fa-youtube"></i> YouTube </a>
      </li>
      {% endif %}
      {% if user.tumblr %}
      <li>
        <a class="button tumblr expand" href="http://www.{{ user.tumblr }}.tumblr.com"><i class="fa fa-tumblr"></i> tumblr </a>
      </li>
      {% endif %}
      {% if user.instagram %}
      <li>
        <a class="button instagram expand" href="http://www.instagram.com/{{ user.instagram }}"><i class="fa fa-instagram"></i> Instagram  </a>
      </li>
      {% endif %}
      {% if user.rgsc %}
      <li>
        <a class="button rgsc expand" href="http://www.socialclub.rockstargames.com/member/{{ user.rgsc }}"><i class="fa fa-star"></i> RG Social Club </a>
      </li>
      {% endif %}
      {% if user.steam %}
      <li>
        <a class="button steam expand" href="http://steamcommunity.com/id/{{ user.wikox }}"><i class="fa fa-steam"></i> Steam </a>
      </li>
      {% endif %}
    </ul>
  </div>
</div>

<script>
  $(document).foundation();
</script>

front/templates/accounts/profile/ajax/logs.html
{% load i18n %}
<h2>{% trans 'Logi' %}</h2>
{% if logs %}
  <table class="table-full-width">
    <thead>
      <tr>
        <th>{% trans 'Postać' %}</th>
        <th>{% trans 'Informacje' %}</th>
        <th>{% trans 'Czas' %}</th>
      </tr>
    </thead>
    <tbody>
      {% for log in logs%}
        <tr>
          <td>
            {% if not log.character.hide or request.user.is_staff %}
              {{ log.character }}
            {% else %}
              {% trans 'Postać ukryta' %}
            {% endif %}
          </td>
          <td>
            {% blocktrans with type=log.get_penalty_type_display admin=log.admin admin_url=log.admin.get_absolute_url %}
              <strong>Nadano karę <em>{{ type }}</em> przez <a href="{{ admin_url }}">{{ admin }}</a></strong>
            {% endblocktrans %}
            <br>
              {{ log.reason }}
          </td>
          <td>
            <strong>{{ log.time }}</strong>
            {% if log.expire %}
              <br>
              {% blocktrans with date=log.expire %}Wygasa {{ date }}{% endblocktrans %}
            {% endif %}
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <br>
  <div class="alert-box secondary">
    {% blocktrans %}
      Jedynie administracja oraz właściciel profilu widzi kary starsze niż {{ penalties_visible_for }} dni.
    {% endblocktrans %}
{% else %}
  <div class="alert-box warning">
    {% trans 'Użytkownik nie ma żadnych wpisów w profilu' %}
  </div>
{% endif %}