blog/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('blog.views',
    url(r'^(?:page-(?P<page>[\d]+)/)?$', 'index', name='index'),
    url(r'^(?P<slug>[-\w]+)/$', 'post', name='post'),
)

cloudmta/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Django
    url(r'^admin/', include(admin.site.urls)),

    # Third-party

    # Mine
    url(r'^$', 'pages.views.homepage', name='homepage'),
    url(r'^characters/', include('characters.urls', namespace='characters')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^vehicles/', include('vehicles.urls', namespace='vehicles')),
    url(r'^groups/', include('groups.urls', namespace='groups')),
    url(r'^doors/', include('doors.urls', namespace='doors')),
    url(r'^page/', include('pages.urls', namespace='pages')),
    url(r'^wiki/', include('wiki.urls', namespace='wiki')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
]

pages/urls.py
from django.conf.urls import url, patterns

urlpatterns = patterns('pages.views',
    url(r'^gui/$', 'gui', name='gui'),
)

front/templates/pages/gui.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block container %}
  <div id="homepage">
    <div class="content-panel gui-panel">
      <div class="row">
        <div class="large-12 columns">
            <h1>Interfejs graficzny</h1>
            <p>{% lorem %}</p>
          </div>
        </div>
    </div>
    {# Slider #}
    <ul class="example-orbit" data-orbit>
      <li>
        <img src="{% static 'img/homepage/gui-1.png' %}" alt="Screenshot 1" />
      </li>
      <li>
        <img src="{% static 'img/homepage/gui-2.png' %}" alt="Screenshot 2" />
      </li>
    </ul>
  </div>
{% endblock %}

front/templates/pages/homepage.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block container %}
  <div id="homepage">
    <div class="content-panel title-panel">
      <img class="title-panel-logo"
        alt="CloudMTA" src="{% static 'img/logo-white.svg' %}">
      <h1>Projekt roleplay jakiego jeszcze nie widziałeś</h1>
      <h2>
    </div>
    <div class="content-panel buttons-panel">
      <ul class="large-block-grid-4 small-block-grid-2" id="homepage-gateway-buttons-list" data-equalizer>
        <li>
          <a class="gateway-button-1" data-equalizer-watch href="{% url 'pages:gui' %}">
            <h2>Interfejs graficzny</h2>
          </a>
        </li>
        <li>
          <a class="gateway-button-2" data-equalizer-watch href="{% url 'pages:gui' %}">
            <h2>Ficzer #2</h2>
          </a>
        </li>
        <li>
          <a class="gateway-button-3" data-equalizer-watch href="{% url 'pages:gui' %}">
            <h2>Ficzer #3</h2>
          </a>
        </li>
        <li>
          <a class="gateway-button-4" data-equalizer-watch href="{% url 'pages:gui' %}">
            <h2>Ficzer #4</h2>
          </a>
        </li>
      </ul>
    </div>
  </div>
{% endblock %}